// This defines the structure of a User object
// "?" means the field is optional
export interface User {
  user_id?: number;  // Optional because it's auto-generated by the database
  name: string;
  password: string;
  role: 'user' | 'employee' | 'manager' | 'supplier';  // Union type - can only be one of these values
}

// This is what the API will return (without password for security)
export interface UserResponse {
  user_id: number;
  name: string;
  role: string;
}

// This is what we send when logging in
export interface LoginRequest {
  name: string;
  password: string;
}

// This is what we send when registering
export interface RegisterRequest {
  name: string;
  password: string;
  role: 'user' | 'employee' | 'manager' | 'supplier';
}